//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PesquisaWebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class isbet_pesquisa_desEntities : DbContext
    {
        public isbet_pesquisa_desEntities()
            : base("name=isbet_pesquisa_desEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_pesquisa_usuario> tbl_pesquisa_usuario { get; set; }

        public System.Data.Entity.DbSet<WebApplication1.Models.Participante> Participantes { get; set; }
    }
}
