//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PesquisaWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pesquisa_usuario
    {
        public int id_envio_pesquisa { get; set; }
        public string cd_chave_externo { get; set; }
        public int id_pesquisa { get; set; }
        public string id_usuario_retorno { get; set; }
        public string id_token_retorno { get; set; }
        public string cd_situacao { get; set; }
        public System.DateTime dt_cadastro { get; set; }
    }
}
